### PR TITLE
Add polish (pl) translation

### PR DESCRIPTION
**Pull request by JakubekWeg**

### CODE REVIEW

**Comment by patzly** [comment]
Thank you! Please use Transifex the next time as described in the Readme (also for translating newly added strings), Transifex can't manage translations from pull requests. I will add your translations in Transifex instead of merging your PR.

**Comment by JakubekWeg** [comment]
Ok, got it, didn't see polish in Transifex so did it here. Hope to see translations soon and also thanks for the app – it's really awesome.

**Comment by patzly** [comment]
I see you have requested it, I get the email notifications from Transifex a few days later I think.

**Comment by patzly** [comment]
During import for Transifex there were two errors caused by wrong plural forms (Transifex requires each language to have its correct plurals, for Polish it requires four plural forms:
``` xml
<plurals name="appearance_random_interval_hours">
    <item quantity="one">Co godzinę</item>
    <item quantity="few">Co godzinę</item> <!-- The plural for "few" was missing, I have inserted the plural from "one" -->
    <item quantity="many">Co godzinę</item> <!-- The plural for "many" was missing, I have inserted the plural from "one" -->
    <item quantity="other">Co %1$d godzin(y)</item>
  </plurals>
  <plurals name="appearance_random_interval_days">
    <item quantity="one">Codziennie</item>
    <item quantity="few">Codziennie</item> <!-- The plural for "few" was missing, I have inserted the plural from "one" -->
    <item quantity="many">Codziennie</item> <!-- The plural for "many" was missing, I have inserted the plural from "one" -->
    <item quantity="other">Co %1$d dni</item>
  </plurals>
```

Please go to [Transifex](https://www.transifex.com/patzly/doodle-android/dashboard/) and edit my inserted plural forms so they are correct for your language. You find them by searching for "Every hour" and "Every day". Plurals are edited in Transifex by going to a plural string and selecting and editing each plural form seperately with the blue selection buttons on the right. Thanks for your contributions!

**Pull request closed without merging**
